arm_name: KINOVA_GEN3_2_RIGHT

KINOVA_GEN3_2_RIGHT:

  action_name: "ms_action_name"
  reach_pre_configuration_joint_angles: false
  pre_configuration_max_deviation_deg: 0.6
  pre_configuration_joint_angles_tolerance_deg: 0.1
  pre_configuration_joint_angle_0_deg: 0.0
  pre_configuration_joint_angle_1_deg: 0.0
  pre_configuration_joint_angle_2_deg: 0.0
  pre_configuration_joint_angle_3_deg: 0.0
  pre_configuration_joint_angle_4_deg: 0.0
  pre_configuration_joint_angle_5_deg: 0.0
  pre_configuration_joint_angle_6_deg: 0.0

  PRE_CONDITION:
    constraint_count: 1
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.1
          - NULL
          - NULL
        operator:
          - LESS_THAN
          - NULL
          - NULL

  PER_CONDITION:
    constraint_count: 2
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.8
          - NULL
          - NULL
        operator: 
          - EQUAL
          - NULL
          - NULL

      2:
        type: FORCE_XYZ
        value:
          - 4.0
          - NULL
          - NULL
        operator: 
          - EQUAL
          - NULL
          - NULL          

  POST_CONDITION:
    constraint_count: 2
    number_of_disjunctions: 2
    constraints:
      1:
        type: POSITION_XYZ
        disjunction_id: 0
        value:
          - 0.8
          - NULL
          - NULL
        operator:
          - GREATER_THAN
          - NULL
          - NULL
      2:
        type: TIME_LIMIT
        disjunction_id: 1
        value:
          - 5.0
        operator:
          - GREATER_THAN